---
output: github_document
---

# EpiSoon

*Warning: This package is a work in progress and is currently developed solely with the COVID-19 outbreak in mind. Breaking changes may occur and the authors cannot guarantee support.*

**Aim:** To forecast the time-varying reproduction number and using this to forecast reported case counts. 

## Installation

Install the analysis and all dependencies with: 

```r
remotes::install_github("epiforecasts/EpiSoon", dependencies = TRUE)
```

## Docker

This package was developed in a docker container based on the `rocker/geospatial` docker image. 

To build the docker image run (from the `EpiSoon` directory):

```bash
docker build . -t episoon
```

To run the docker image run:

```bash
docker run -d -p 8787:8787 --name episoon -e USER=episoon -e PASSWORD=episoon episoon
```

The rstudio client can be found on port :8787 at your local machines ip. The default username:password is epinow:epinow, set the user with -e USER=username, and the password with - e PASSWORD=newpasswordhere. The default is to save the analysis files into the user directory.

To mount a folder (from your current working directory - here assumed to be `tmp`) in the docker container to your local system use the following in the above docker run command (as given mounts the whole `episoon` directory to `tmp`).

```{bash, eval = FALSE}
--mount type=bind,source=$(pwd)/tmp,target=/home/EpiSoon
```

To access the command line run the following:

```{bash, eval = FALSE}
docker exec -ti episoon bash
```
